baseURL = "https://blackhuang-blog.netlify.app"     # 你的網站基本 URL，請替換成你的網址
languageCode = "en-us"               # 語言代碼
title = "My New Hugo Site"           # 你網站的標題
theme = "github.com/gethinode/hinode"            # 使用的主題名稱（如果有安裝主題的話）

# 以下是一些可選的其他設定
[params]
  description = "嗨嗨！這是我的個人部落格"
  author = "Howard Huang"

[[module.imports]]
path = "github.com/gethinode/hinode"

[menu]
  [[menu.main]]
    name = "首頁"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "關於"
    url = "/about/"
    weight = 2
