backend:
  name: git-gateway
  branch: master
  auth:
    roles: ["admin", "editor"]  # 定義角色

publish_mode: editorial_workflow
media_folder: "static/images/uploads"  # 上傳媒體的路徑
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Updated Date", name: "updated", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "featured_image", widget: "image"}
      - {label: "Tag", name: "tag", widget: "list"}
      - {label: "Category", name: "category", widget: "select", options: ["旅遊 Travel", "攝影 Photos", "隨筆 Notes"]}
